services:
    _defaults:
        autowire: true      # automatically injects dependencies in your services
        autoconfigure: true # automatically registers your services as commands, event subscribers, etc.
        public: false       # disallow fetch services directly from the container via $container->get()

    Acme\App\Presentation\Controller\:
        resource: '%kernel.project_dir%/src/Presentation/Controller/*Controller.php'
        tags: ['controller.service_arguments']
