services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Disallow fetch services directly from the container via $container->get()

    # There are several implementations of this interface, so we need to choose one of them
#    Accel\App\Core\Port\MapperInterface:
#        class: Acme\App\Infrastructure\Persistence\Doctrine\KeyValueStorage